import { BRAND } from "@/lib/brand";
import type { SettingsState } from "./types";

export function buildSettingsSeed(): SettingsState {
  const installed = new Date().toISOString();
  return {
    school: {
      name: BRAND.name,
      motto: "Excellence in Education",
      logoDataUrl: null,
      address: "123 Education Avenue",
      city: "Mogadishu",
      country: "Somalia",
      phone: "+252 61 000 0000",
      email: "info@ekulmis.edu",
      website: "https://ekulmis.edu",
      principalName: "Dr. Ahmed Hassan",
      academicYear: "2024-2025",
      currency: "USD",
      timezone: "Africa/Mogadishu",
      language: "en",
      documentHeaderLayout: "LEFT",
      reportHeader: "",
      reportFooter: "",
    },
    branding: {
      primaryColor: "#3b82f6",
      secondaryColor: "#6366f1",
      accentColor: "#0ea5e9",
      faviconDataUrl: null,
      loginBackgroundDataUrl: null,
      loginTitle: BRAND.name,
      footerText: `© ${new Date().getFullYear()} ${BRAND.name}. All rights reserved.`,
    },
    academic: {
      activeAcademicYear: "2024-2025",
      schoolLevel: "K-12",
      passingPercentage: 50,
      gradeScale: "A-F",
      defaultAttendanceStatus: "PRESENT",
      graduationClass: "Grade 12",
      autoPromote: false,
    },
    students: {
      idPrefix: "SHMM",
      startingNumber: 1,
      idLength: 6,
      portalLoginEnabled: true,
      requirePhone: false,
      allowPhotoUpload: true,
      studentHeader: "",
      studentFooter: "",
    },
    teachers: {
      idPrefix: "TSHMM",
      defaultPassword: "Teacher@123",
      portalEnabled: true,
      defaultViewStudents: false,
      morningShiftStart: "07:30",
      afternoonShiftStart: "13:00",
      teacherHeader: "",
      teacherFooter: "",
    },
    parents: {
      idPrefix: "PSHMM",
      portalEnabled: true,
      autoAccountCreation: true,
      usernameFormat: "FIRST_NAME",
      defaultPassword: "Parent@123",
      parentHeader: "",
      parentFooter: "",
    },
    examinations: {
      maxTerms: 3,
      defaultExamStatus: "DRAFT",
      passingPercentage: 50,
      resultPublishing: true,
      resultLocking: true,
      studentResultPortal: true,
      parentResultPortal: true,
      publicResultPortal: true,
      blockResultFeature: true,
    },
    grades: [
      { min: 90, max: 100, grade: "A" },
      { min: 80, max: 89, grade: "B" },
      { min: 70, max: 79, grade: "C" },
      { min: 60, max: 69, grade: "D" },
      { min: 50, max: 59, grade: "E" },
      { min: 0, max: 49, grade: "F" },
    ],
    fees: {
      monthlyFeeSystem: true,
      billingMode: "MONTHLY",
      monthSetupDay: 25,
      academicMonths: 10,
      billingStartMonth: 9,
      billingEndMonth: 6,
      allowPartialPayment: true,
      allowAdvancePayment: true,
      carryForward: true,
      currencySymbol: "$",
      receiptPrefix: "RCP",
      receiptHeader: "",
      receiptFooter: "This is a computer-generated receipt. Thank you for your payment.",
    },
    salary: {
      payrollDay: 28,
      allowPartialSalary: false,
      currency: "USD",
      payslipHeader: "",
      payslipFooter: "This is a system-generated payslip.",
    },
    expenses: {
      approvalWorkflow: true,
      defaultCategories: ["Utilities", "Supplies", "Maintenance", "Transport", "Events"],
      attachmentSizeLimitMb: 5,
      expenseHeader: "",
      expenseFooter: "",
    },
    attendance: {
      startTime: "07:00",
      endTime: "14:00",
      lateTime: "07:30",
      excusedEnabled: true,
      lockTime: "16:00",
    },
    quiz: {
      maxAttempts: 2,
      autoSubmit: true,
      autoSave: true,
      showResultsImmediately: true,
      questionRandomization: false,
    },
    notifications: {
      inApp: true,
      email: true,
      sms: false,
      whatsapp: false,
      events: {
        newStudent: true,
        feeCollection: true,
        examPublished: true,
        quizPublished: true,
        attendanceAlert: true,
        resultPublished: true,
      },
    },
    email: {
      smtpHost: "smtp.example.com",
      smtpPort: 587,
      smtpUsername: "",
      smtpPassword: "",
      senderName: BRAND.name,
      senderEmail: "noreply@ekulmis.edu",
    },
    security: {
      minPasswordLength: 8,
      requireComplexity: true,
      requireUppercase: true,
      requireNumber: true,
      sessionTimeoutMinutes: 30,
      loginAttemptLimit: 5,
      twoFactorEnabled: false,
      ipRestriction: "",
    },
    backup: {
      dailyAuto: true,
      weeklyAuto: true,
      monthlyAuto: true,
      retentionDays: 30,
      location: "local",
      lastBackupAt: null,
    },
    license: {
      licenseKey: "EKULMIS-DEMO-2025",
      active: true,
      expiresAt: new Date(new Date().getFullYear() + 1, 11, 31).toISOString(),
    },
    system: {
      systemName: BRAND.name,
      version: "1.0.0",
      buildNumber: "2025.07.001",
      installationDate: installed,
      databaseType: "PostgreSQL (Demo: localStorage)",
      serverTime: new Date().toISOString(),
    },
    audit: [],
    backups: [],
  };
}
