import { BRAND } from "@/lib/brand";
import { getSettings } from "@/lib/settings/store";
import { escapeHtml, PRINT_HEADER_CSS, printHeaderHtml } from "@/lib/print/header";
import type { ReportColumn, ReportData } from "./types";

interface PrintOpts {
  title: string;
  academicYear?: string;
  data: ReportData;
  preparedBy?: string;
}

export function printReport(opts: PrintOpts) {
  const { reportHeader, reportFooter } = getSettings().school;
  const now = new Date();
  const head = opts.data.columns.map((c) => `<th>${c.label}</th>`).join("");
  const body = opts.data.rows
    .map(
      (row) =>
        `<tr>${opts.data.columns.map((c) => `<td>${row[c.key] ?? ""}</td>`).join("")}</tr>`,
    )
    .join("");

  const summary = opts.data.summary
    .map((s) => `<div class="sum"><span>${s.label}</span><b>${s.value}</b></div>`)
    .join("");

  const html = `<!doctype html><html><head><meta charset="utf-8"/><title>${opts.title}</title>
  <style>
    * { font-family: system-ui, -apple-system, Segoe UI, sans-serif; box-sizing: border-box; }
    body { padding: 32px 40px; color: #0f172a; font-size: 12px; }
    ${PRINT_HEADER_CSS}
    .summary { display:flex; flex-wrap:wrap; gap:12px; margin-bottom:20px; }
    .sum { border:1px solid #e2e8f0; border-radius:8px; padding:10px 14px; min-width:120px; }
    .sum span { display:block; font-size:10px; color:#64748b; text-transform:uppercase; }
    .sum b { font-size:16px; }
    table { width:100%; border-collapse:collapse; }
    th, td { border:1px solid #e2e8f0; padding:7px 9px; text-align:left; }
    th { background:#f1f5f9; font-weight:600; font-size:11px; text-transform:uppercase; }
    .foot { margin-top:28px; padding-top:16px; border-top:1px solid #e2e8f0; display:flex; justify-content:space-between; font-size:11px; color:#64748b; }
    .sig { margin-top:40px; display:flex; justify-content:space-between; }
    .sig div { width:200px; border-top:1px solid #94a3b8; padding-top:8px; text-align:center; font-size:11px; color:#64748b; }
    @media print { body { padding: 20px; } }
  </style></head><body>
    ${printHeaderHtml(
      `${reportHeader || BRAND.tagline}`,
      `<div class="ek-subtitle"><b>${escapeHtml(opts.title)}</b>${opts.academicYear ? ` · Academic Year ${escapeHtml(opts.academicYear)}` : ""}</div>`,
    )}
    ${summary ? `<div class="summary">${summary}</div>` : ""}
    <table><thead><tr>${head}</tr></thead><tbody>${body || `<tr><td colspan="${opts.data.columns.length}" style="text-align:center;color:#64748b;">No records</td></tr>`}</tbody></table>
    <div class="foot">
      <span>${reportFooter || `Generated by: ${opts.preparedBy ?? "Admin User"}`}</span>
      <span>${now.toLocaleString()} · ${opts.data.rows.length} record(s)</span>
    </div>
    <div class="sig">
      <div>Prepared By</div>
      <div>Authorized Signature</div>
    </div>
    <script>window.onload = () => window.print();</script>
  </body></html>`;

  const w = window.open("", "_blank", "width=960,height=720");
  if (!w) return;
  w.document.write(html);
  w.document.close();
}

export function exportReportCsv(title: string, columns: ReportColumn[], rows: Record<string, string | number>[]) {
  const header = columns.map((c) => c.label).join(",") + "\n";
  const body = rows
    .map((row) => columns.map((c) => String(row[c.key] ?? "").replace(/,/g, " ")).join(","))
    .join("\n");
  const blob = new Blob([header + body], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.toLowerCase().replace(/\s+/g, "-")}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

/** PDF via browser print dialog (Save as PDF). */
export function downloadReportPdf(opts: PrintOpts) {
  printReport(opts);
}
